spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: graphql-springboot-example
  servlet:
    multipart:
      enabled: true
      location: /tmp
server:
  port: 8086
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

graphql:
  servlet:
    # Sets if GraphQL servlet should be created and exposed. If not specified defaults to "true".
    enabled: true
    # Sets the path where GraphQL servlet will be exposed. If not specified defaults to "/graphql"
    mapping: /graphql
    cors-enabled: true
    cors:
      allowed-origins: http://localhost:8080
      allowed-methods: GET, HEAD, POST, OPTIONS
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
  altair:
    enabled: true
    mapping: /altair
    static:
      base-path: /
    page-title: Altair
    cdn:
      enabled: false
      version: 4.0.2
    options:
      endpoint-url: /graphql
directives:
  package: com.example.graphqldemo.schema.directives